name: Python CI

on: push

jobs:
  test:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install R and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base
        echo "R installed successfully"

    - name: Install cdo and poetry
      run: |
        sudo apt-get update
        sudo apt-get install cdo
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - id: cache-poetry
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies if changed
      if: ${{ steps.cache-poetry.outputs.cache-hit != 'true' }}
      run: |
        poetry env use python${{ matrix.python-version }}
        poetry install --extras "complete"
        poetry run pip install -e .
        poetry run pip install --upgrade pip setuptools

    - name: Test with pytest (full)
      if: github.ref == 'refs/heads/master'
      run: |
        poetry run py.test -m "not online" -v

    - name: Test with pytest (fast)
      if: github.ref != 'refs/heads/master'
      run: |
        poetry run py.test -m "not online and not slow" -v

    - name: Code Quality
      run: poetry run black . --check
